fix custom action

diff --git a/.github/actions/tester/action.yml b/.github/actions/tester/action.yml
--- a/.github/actions/tester/action.yml
+++ b/.github/actions/tester/action.yml
@@ -5,6 +5,16 @@ runs:
   using: "composite"
   steps:
     - run: |
-        echo "Testing app..."
-        curl http://localhost:8000
+        echo "Testing app inside container..."
+
+        CONTAINER_ID=$(docker ps -q)
+
+        for i in {1..10}; do
+          docker exec $CONTAINER_ID curl http://localhost:8000 && exit 0
+          echo "Retrying..."
+          sleep 3
+        done
+
+        echo "App failed"
+        exit 1
       shell: bash
